"""Fix missing loan_overdue_days column

Revision ID: 27ad0c4ba539
Revises: add_contact_message_id
Create Date: 2026-02-02 19:12:25.606081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27ad0c4ba539'
down_revision = 'add_contact_message_id'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('library_id',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.alter_column('library_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('read_by_admin',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               nullable=True)
        batch_op.alter_column('is_resolved',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               nullable=True)
        batch_op.drop_column('email')

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_overdue_days', sa.Integer(), nullable=False))

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'user'"),
               existing_nullable=False)

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               server_default=sa.text("'pending'"),
               existing_nullable=False)

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_column('loan_overdue_days')

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
        batch_op.alter_column('is_resolved',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               nullable=False)
        batch_op.alter_column('read_by_admin',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               nullable=False)
        batch_op.alter_column('library_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               server_default=sa.text("'available'"),
               existing_nullable=False)
        batch_op.alter_column('library_id',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text('1'),
               existing_nullable=False)

    # ### end Alembic commands ###
