"""Add Location model for book shelf information

Revision ID: 42404df2530c
Revises: add_user_names
Create Date: 2026-01-27 15:53:11.400750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42404df2530c'
down_revision = 'add_user_names'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('shelf', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    # ### end Alembic commands ###
