"""add preferred_locale to user

Revision ID: a8658df6c988
Revises: b6abb05c0cb1
Create Date: 2026-02-27 13:02:48.665398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = 'a8658df6c988'
down_revision = 'b6abb05c0cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # drop any leftover temp table from a previous failed upgrade
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_user')

    # skip if column already present (previous partial run)
    # use SQLAlchemy inspector which works across databases
    conn = op.get_bind()
    insp = sa.inspect(conn)
    existing = [c['name'] for c in insp.get_columns('user')]
    if 'preferred_locale' in existing:
        return

    # add column as nullable with default so existing rows get a value
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_locale', sa.String(length=5), nullable=True, server_default='en'))

    # populate any NULLs just in case (batch copy may not apply default)
    op.execute("UPDATE user SET preferred_locale='en' WHERE preferred_locale IS NULL")

    # now make it non-nullable and drop the server default
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'preferred_locale',
            nullable=False,
            server_default=None,
            existing_type=sa.String(length=5),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferred_locale')

    # ### end Alembic commands ###
