"""add contact_message_id to notification

Revision ID: add_contact_message_id
Revises: update_contact_message_conversations
Create Date: 2026-02-01 20:43:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_contact_message_id'
down_revision = 'update_contact_message_conversations'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_message_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notification_contact_message',
                                    'contact_message', ['contact_message_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_contact_message', type_='foreignkey')
        batch_op.drop_column('contact_message_id')

    # ### end Alembic commands ###
