"""Add tenant_id to comment table

Revision ID: add_comment_tenant_id
Revises: 920b88e6f5b5
Create Date: 2026-02-19 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_comment_tenant_id'
down_revision = '920b88e6f5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'tenant_id')
    # ### end Alembic commands ###
