"""Add Library, roles, and access request models

Revision ID: ee2182cf18f2
Revises: 8904ea11c501
Create Date: 2026-01-22 21:13:55.748702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2182cf18f2'
down_revision = '8904ea11c501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_name'), ['name'], unique=True)

    op.create_table('library_access_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_libraries',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'library_id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('library_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_book_library_id_library', 'library', ['library_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('role')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_library_id_library', type_='foreignkey')
        batch_op.drop_column('library_id')

    op.drop_table('user_libraries')
    op.drop_table('library_access_request')
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_name'))

    op.drop_table('library')
    # ### end Alembic commands ###
